// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSConstant
{
        public const string achievement_good_50_points = "CgkI2_7tgqUIEAIQDQ"; // <GPGSID>
        public const string achievement_chicken_wings_100_points = "CgkI2_7tgqUIEAIQAw"; // <GPGSID>
        public const string achievement_ride_the_wings_of_pestilance_200_points = "CgkI2_7tgqUIEAIQBg"; // <GPGSID>
        public const string achievement_excellent_100_points = "CgkI2_7tgqUIEAIQDA"; // <GPGSID>
        public const string event_amount_of_endless_games_started = "CgkI2_7tgqUIEAIQBw"; // <GPGSID>
        public const string achievement_buffalo_wings_120_points = "CgkI2_7tgqUIEAIQBA"; // <GPGSID>
        public const string event_score_endless_mode = "CgkI2_7tgqUIEAIQCA"; // <GPGSID>
        public const string achievement_bun_venit_20_points = "CgkI2_7tgqUIEAIQAQ"; // <GPGSID>
        public const string achievement_wingin_it_160_points = "CgkI2_7tgqUIEAIQBQ"; // <GPGSID>
        public const string event_game_opened = "CgkI2_7tgqUIEAIQCg"; // <GPGSID>
        public const string leaderboard_endless_mode = "CgkI2_7tgqUIEAIQAg"; // <GPGSID>
        public const string leaderboard_multiplayer_mode = "CgkI2_7tgqUIEAIQDg"; // <GPGSID>
        public const string event_health_potions_picked_up = "CgkI2_7tgqUIEAIQCQ"; // <GPGSID>
        public const string event_multiplayer_match_started = "CgkI2_7tgqUIEAIQDw"; // <GPGSID>
        public const string event_coin_picked_up = "CgkI2_7tgqUIEAIQEA"; // <GPGSID>
        public const string event_store_default_skin_bought = "CgkI2_7tgqUIEAIQEQ"; // <GPGSID>
        public const string achievement_next = "CgkI2_7tgqUIEAIQEg"; // <GPGSID>
}

