public class GPMPEvents {

    public enum Types {

        // Match making
        GPMP_MATCH_MAKING_DONE,
        GPMP_SEARCH_QUICK_MATCH,
        GPMP_START_WITH_INVITE,
        GPMP_CANCEL_MATCH_MAKING,
        GPMP_LEAVE_GAME,
        GPMP_REPORT_ROOM_SETUP_PROGRESS,
        GPMP_VIEW_INVITES,
        GPMP_OPPONENT_FOUND,
        GPMP_SHOW_ERROR_MESSAGE,

        // Game events
        GPMP_MATCH_INFO_READY,
        GPMP_UPDATE_MY_POSITION,
        GPMP_UPDATE_OPPONENT_POSITION,
        GPMP_OPPONENT_SKIN_RECIEVED,
        GPMP_MESSAGE_RECIEVED,
        GPMP_PLAYER_READY,
        GPMP_OPPONENT_READY,
        GPMP_READY_ACKNOWLEDGE,
        GPMP_START_GAME,
        GPMP_OPPONENT_LEFT,
        GPMP_GAME_ITEM_SPAWNED,
        GPMP_GAME_ITEM_RECIEVED,
        GPMP_PLAYER_DIED,
        GPMP_OPPONENT_DIED
    };
}
